/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/texyures/Apartment.glb -o src/components/apartment.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

 const Apartment=(props)=> {
  const { nodes, materials } = useGLTF('/texyures/Apartment.glb')
  return (
    <group {...props} dispose={null} rotation={[0,-1.2,0]} position={[6,-7,0]}>
      <mesh geometry={nodes.Apartment_mesh.geometry} material={materials.Apartment_mat1} />
    </group>
  )
}

useGLTF.preload('/texyures/Apartment.glb')
export default Apartment;