/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/texyures/cabin.glb -o src/components/cabin.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

const  Cabin=(props)=> {
  const { nodes, materials } = useGLTF('/texyures/cabin.glb')
  return (
    <group {...props} dispose={null} scale={0.02}>
      <mesh geometry={nodes.Cottage.geometry} material={materials.lambert3SG} />
      <mesh geometry={nodes.Door.geometry} material={materials.lambert3SG} />
    </group>
  )
}

useGLTF.preload('/texyures/cabin.glb')
export default Cabin